php7:
  container_name: jetphp-php7
  build: .
  dockerfile: ./etc/docker/dockerfile_php_7
  volumes:
    - .:/var/www/html
    - ./etc/php:/usr/local/etc/php
    - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
    - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
  ports:
    - "5005:80"
  links:
    - mysql

mysql:
  container_name: jetphp-mysql
  image: mysql:5.7
  ports:
    - "3307:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=jetphp
  volumes: 
    - ./etc/mysql:/docker-entrypoint-initdb.d
